# Generated by Django 5.1.4 on 2024-12-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
